# DEV mode
DEV = 'True'

# Directories and filenames
GAUGE_CALIBRATION_FILE_XML = 'gauge_params.xml'  # Name of the gauge calibration_data file
TRAIN_IMAGE_NAME = 'train_image.jpg'  # Name of the training image
NEEDLE_IMAGE_NAME = 'needle_image.jpg'  # Name of the needle image
TRAIN_SET_DIR_NAME = 'train_set'  # Name of the training set directory
XML_FILE_NAME = "camera_{}_analog_gauge_{}"  # Name of the gauge calibration_data file
VALIDATION_SET_DIR_NAME = 'validation_set'  # Name of the validation set directory
REPORT_PLT_NAME = 'visual_test_report.png'  # Name of the report plot

# UI parameters
WINDOW_SIZE = [1500, 1500] # Default Calibrator app window size (width, height)
EDIT_IMAGE_SIZE = [500, 500] # Default edit image window size (pixels)
TRAIN_IMAGE_SIZE = 64 # Default train image size (pixels)
REPORT_PLT_SIZE = 15 # Default report plot size (inches)

# MODEL parameters
LOSS_THRESHOLD = 0.002  # Threshold for the loss function
BATCH_SIZE = 64 # Batch size for dataset loading and training
BATCH_MULTIPLIER = 3 # Batch multiplier for building the dataset
EPOCHS = 150 # Number of epochs for training
EPOCHS_ADD = 20 # Number of epochs for additional training
MAX_EPOCHS = 250 # Maximum number of epochs for training
LEARNING_RATE = 0.001 # Learning rate for the model
AUTO_ADD_EPOCHS = 'True' # Automatically add epochs to the model when training if the loss is below the threshold
TORCH_SEED = 147 # Seed for the torch random number generator
NUM_WORKERS = 1 # Number of workers for dataset loading
DEFAULT_MODEL_TYPE = 'best' # Default model type for loading (best or latest)
MODEL_VERSION = '1.0' # Model version for saving

# Gauge Types
GAUGE_TYPES = ['analog', 'digital'] # List of gauge types supported by the app

# Other
TEST_REPORT_IMAGE_TILE = 8 # Number of images in the test report image tile